export const StoreProducts = [
  {
    id: 1,
    title: "3x3",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/61vjyP4OmFL._AC_SX425_.jpg",
    price: 5,
    company: "valk",
    info: "aaa",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "2x2",
    img:
      "https://cdn.shopify.com/s/files/1/0051/8173/5030/products/cyclone-boys-2x2_300x300.jpg?v=1546799150",
    price: 4,
    company: "cyclone boys",
    info: "bbb",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "skewb",
    img: "https://m.media-amazon.com/images/I/51bgDqD7Q5L._SR500,500_.jpg",
    price: 8,
    company: "yj",
    info: "ccc",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "ghost cube",
    img:
      "https://vignette.wikia.nocookie.net/rubiks/images/2/2c/Ghost3x3.jpg/revision/latest/scale-to-width-down/340?cb=20170814203113",
    price: 4,
    company: "qiyi",
    info: "ddd",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "megaminx",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/61r%2BUos3oTL._SY355_.jpg",
    price: 10,
    company: "moyu",
    info: "eee",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "gear cube extreme",
    img: "https://wizzon.com/wp-content/uploads/product-images/TYPZ02468-1.jpg",
    price: 5,
    company: "valk",
    info: "aaa",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "4x4",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/51ddvOvhfNL._AC_SX425_.jpg",
    price: 4,
    company: "cyclone boys",
    info: "bbb",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "leaf cube",
    img:
      "https://i.pinimg.com/originals/22/4c/15/224c1562ed29bdae723f5b98c85b7df2.jpg",
    price: 8,
    company: "yj",
    info: "ccc",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "pyraminx",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/61Hy-T3DvxL._SL1200_.jpg",
    price: 4,
    company: "qiyi",
    info: "ddd",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "megaminx",
    img:
      "https://images-na.ssl-images-amazon.com/images/I/61r%2BUos3oTL._SY355_.jpg",
    price: 10,
    company: "moyu",
    info: "eee",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const DetailProduct = {
  id: 6,
  title: "mastermorphix",
  img:
    "https://ae01.alicdn.com/kf/HTB1nnXUfHsTMeJjSszdq6AEupXaC.jpg?size=21473&height=600&width=800&hash=c6d750072691a6e76108feaf5c55c1d5",
  price: 10,
  company: "yj",
  info:
    "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque, consectetur error eum assumenda doloribus sequi ea sint doloremque qui, cupiditate ipsum recusandae voluptates distinctio autem dolorem pariatur maiores! Dolores, molestiae.",
  inCart: false,
  count: 0,
  total: 0,
};
